services:
  server:
    image: portainer/portainer-ce:2.19.4
    command: --tlsskipverify
    volumes:
      - server-data:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: none
    external: true

volumes:
  server-data:
