services:
  agent:
    image: portainer/agent:2.18.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  server:
    image: portainer/portainer-ce:2.18.3
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - server_data:/data
    ports:
      - target: 9443
        published: 9443
        mode: host
      - target: 9000
        published: 9000
        mode: host
      - target: 8000
        published: 8008
        mode: host
    networks:
      - bridge
      - agent_network
      - caddy_network
    labels:
      caddy: :80
      caddy.redir: /admin/portainer /admin/portainer/
      caddy.handle_path: /admin/portainer/*
      caddy.handle_path.reverse_proxy: "{{upstreams 9000}}"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    name: portainer-agent
    driver: overlay
    attachable: true
  caddy_network:
    name: caddy-ingress
    external: true
  bridge:
    name: bridge
    external: true

volumes:
  server_data:
