schema: 0.1

package:
  version: 0.1.0
  description: Admin GUI for Docker
  maintainers:
  - name: Ethan Li
    email: lietk12@gmail.com
  license: Zlib
  sources:
  - https://github.com/portainer/portainer

deployment:
  name: portainer
