# FIXME: if we will still use hostapd once we migrate to NetworkManager (as part of the migration to
# RPiOS 12 bookworm), we should make a service which automatically assembles
# /etc/hostapd/hostapd.conf.d files into a
# /run/overlays/generated/etc/hostapd/hostapd.conf file
# Configure settings for the local environment
# FIXME: the country code needs to be updated based on user settings
country_code=US
# WLAN channel; prefer values from 1-11 for compatibility with national regulations:
# FIXME: the channel needs to be updatable based on user settings
channel=8

# Host the wireless AP from the Raspberry Pi's on-board wifi interface
interface=wlan0
driver=nl80211

# Configure modes
# Use the 2.4 GHz band (5 GHz is restricted in various ways by various countries):
hw_mode=g
# Support 802.11n:
ieee80211n=1
# Support QoS, also required for full speed on 802.11n:
wmm_enabled=1
# Limit frequencies used to those allowed in the country:
ieee80211d=1

# Configure the SSID
# The ssid line is automatically generated. Any changes you make to it will be lost with the next
# boot/reboot. If you want to change the format of the SSID and you want your changes to persist
# across reboots, create and edit a new file at /etc/planktoscope/hostapd-ssid with the desired
# ssid, and then restart the planktoscope-org.update-hostapd-ssid-machine-name system service,
# and then restart the hostapd system service.
# In that file, the string "{machine-name}" will be automatically replaced with the machine-specific
# name, which will look something like "metal-slope-23501".
# Warning: the Wi-FI hotspot SSID is not allowed to be longer than 32 bytes.
ssid=raspberrypi
# Advertise the SSID to devices scanning for networks:
ignore_broadcast_ssid=0

# Configure Auth
# Accept all MAC addresses except those in denylist:
macaddr_acl=0
# Only use WPA for auth:
auth_algs=1
# Only use WPA2:
wpa=2
wpa_passphrase=copepode
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP TKIP
rsn_pairwise=CCMP
