schema: 0.1

package:
  version: 0.1.0
  description: Reverse proxy for web services
  maintainers:
  - name: Ethan Li
    email: lietk12@gmail.com
  license: MIT
  sources:
  - https://github.com/lucaslorentz/caddy-docker-proxy

deployment:
  name: caddy-ingress
