schema: 0.1

package:
  version: 0.1.0
  description: An isolated Node-RED instance for prototyping
  maintainers:
  - name: Ethan Li
    email: lietk12@gmail.com
  license: Apache-2.0
  sources:
  - https://github.com/node-red/node-red

deployment:
  name: nodered-sandbox
