services:
  server:
    image: ghcr.io/sargassum-world/pslocal:0.3.8
    volumes:
      - server_data:/data
    ports:
      - 3000:3000
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - bridge
    environment:
      DATABASE_URI: file:/data/db.sqlite3
      LOCALHOST_DEFAULT: host.docker.internal

networks:
  bridge:
    external: true

volumes:
  server_data:
