schema: 0.1

package:
  version: 0.1.0
  description: An experimental GUI for the PlanktoScope with configurable automation
  maintainers:
  - name: Ethan Li
    email: lietk12@gmail.com
  license: Apache-2.0
  sources:
  - https://github.com/sargassum-world/pslive

deployment:
  name: pslocal
