services:
  server:
    image: ghcr.io/planktoscope/project-docs:2024.0.0-alpha.1-minimal
    volumes:
      - server-data:/data
      - server-config:/config

networks:
  default:
    name: none
    external: true

volumes:
  server-data:
  server-config:
