services:
  server:
    image: ghcr.io/planktoscope/project-docs:2023.9.0-beta.2
    volumes:
      - server_data:/data
      - server_config:/config

networks:
  default:
    name: none
    external: true

volumes:
  server_data:
  server_config:
