services:
  server:
    image: ghcr.io/planktoscope/device-portal:0.1.6
    volumes:
      - type: bind
        source: /sys/firmware/devicetree/base/serial-number
        # TODO: make a feature for RPi-specific support vs. a Docker volume vs. a test machine name (0xdeadc0de)
        target: /serial-number
        # By default, Docker masks /sys/firmware inside the container. For more information, see
        # https://github.com/moby/moby/issues/43419
        read_only: true
    networks:
      - caddy-ingress
    environment:
      - MACHINENAME_SNFILE=/serial-number
    labels:
      caddy: :80
      caddy.handle_0: /
      caddy.handle_0.reverse_proxy: "{{upstreams 3000}}"
      caddy.handle_1: /favicon.ico
      caddy.handle_1.reverse_proxy: "{{upstreams 3000}}"
      caddy.handle_2: /app/*
      caddy.handle_2.reverse_proxy: "{{upstreams 3000}}"
      caddy.handle_3: /static/*
      caddy.handle_3.reverse_proxy: "{{upstreams 3000}}"
      caddy.handle_4: /fonts/*
      caddy.handle_4.reverse_proxy: "{{upstreams 3000}}"

networks:
  caddy-ingress:
    external: true
