services:
  server:
    image: filebrowser/filebrowser:v2.24.2
    volumes:
      - /home/pi/data:/home/pi/data
      - server_data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/home/pi/data

networks:
  default:
    name: none
    external: true

volumes:
  server_data: {}
