services:
  server:
    image: filebrowser/filebrowser:v2.24.2
    volumes:
      - /home/pi/data:/home/pi/data
      - server_data:/database
    networks:
      - caddy-ingress
    environment:
      - FB_PORT=80
      - FB_BASEURL=/ps/data/browse
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/home/pi/data
      - FB_NOAUTH=true
    labels:
      caddy: :80
      caddy.redir: /ps/data/browse /ps/data/browse/
      caddy.handle: /ps/data/browse/*
      caddy.handle.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy-ingress:
    external: true

volumes:
  server_data: {}
