services:
  server:
    image: filebrowser/filebrowser:v2.23.0
    volumes:
      - /:/root
      - server_data:/database
    networks:
      - caddy-ingress
    environment:
      - FB_PORT=80
      - FB_BASEURL=/admin/fs
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/root
      - FB_NOAUTH=true
    labels:
      caddy: :80
      caddy.redir: /admin/fs /admin/fs/
      caddy.handle: /admin/fs/*
      caddy.handle.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy-ingress:
    external: true

volumes:
  server_data: {}
