services:
  node-exporter:
    image: prom/node-exporter:v1.7.0
    command:
      - '--path.rootfs=/host'
    network_mode: host # TODO: document port 9100 in the device-portal's API section
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    labels:
      prometheus-job: node-exporter
      prometheus-__scrape-interval__: 5s
      prometheus-__address__: host.docker.internal:9100

networks:
  default:
    name: none
    external: true
