services:
  server:
    volumes:
      - type: bind
        source: /sys/firmware/devicetree/base/serial-number
        target: /serial-number
        # By default, Docker masks /sys/firmware inside the container. For more information, see
        # https://github.com/moby/moby/issues/43419
        read_only: true
    environment:
      - MACHINENAME_SNFILE=/serial-number
