services:
  server:
    command:
      - --web.external-url=/admin/prometheus/
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /admin/prometheus /admin/prometheus/
      caddy.handle: /admin/prometheus/*
      caddy.handle.reverse_proxy: "{{upstreams 9090}}"

networks:
  caddy-ingress:
    external: true
