#!/bin/bash -eu

# Unmount overlays:
sudo systemctl stop overlay-etc.service
sudo systemctl stop overlay-usr.service

# Clean up any unnecessary apt files:
sudo apt-get autoremove -y
sudo apt-get clean -y

# Clear machine-id so that it will be regenerated on the next boot
# (refer to https://www.freedesktop.org/software/systemd/man/latest/machine-id.html):
sudo bash -c 'printf "" > /var/lib/dbus/machine-id'
sudo bash -c 'printf "uninitialized\n" > /etc/machine-id'

# Clear other secrets (refer to https://systemd.io/BUILDING_IMAGES/):
sudo rm -f /var/lib/systemd/random-seed
sudo rm -f /var/lib/systemd/credential.secret

# Remove SSH keys:
sudo rm -f /etc/ssh/ssh_host_*_key*

# Make the OS resize the partitions to fill the SD card on the next boot:
if ! grep 'init=/usr/lib/raspberrypi-sys-mods/firstboot' /boot/cmdline.txt > /dev/null; then
  sudo sed 's~$~ init=/usr/lib/raspberrypi-sys-mods/firstboot~' -i /boot/cmdline.txt
fi

sudo shutdown now
