services:
  server:
    image: ghcr.io/planktoscope/device-backend-processing-segmenter:sha-a070c89
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  default:
    name: none
    external: true
