services:
  server:
    volumes:
      - /run/machine-name:/var/lib/planktoscope/machine-name
      - /home/pi/data:/home/pi/data
      - /home/pi/device-backend-logs/processing/segmenter:/home/pi/device-backend-logs/processing/segmenter
