services:
  server:
    image: ghcr.io/planktoscope/device-backend-processing-segmenter:2024.0.0-alpha.1
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  default:
    name: none
    external: true
