services:
  reverse-proxy:
    image: lucaslorentz/caddy-docker-proxy:2.8.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - server_data:/data
      - server_config:/config
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  default:
    name: none
    external: true

volumes:
  server_data:
  server_config:
