services:
  reverse-proxy-config:
    image: alpine:3.18.2
    command: sh -c 'while sleep 3600; do :; done'
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.handle_path: /ps/hal/camera/streams/preview.mjpg
      caddy.handle_path.rewrite: "* /stream.mjpg"
      caddy.handle_path.reverse_proxy: host.docker.internal:8000

networks:
  caddy-ingress:
    external: true
