services:
  whoami:
    image: containous/whoami
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /demo/whoami /demo/whoami/
      caddy.handle_path: /demo/whoami/*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy-ingress:
    external: true
