schema: 0.1

package:
  version: 0.1.0
  description: A hello-world and whoami demo
  maintainers:
  - name: Ethan Li
    email: lietk12@gmail.com
  license: Apache-2.0
  sources:
  - https://github.com/nginxinc/NGINX-Demos
  - https://github.com/traefik/whoami

deployment:
  name: simple-demo
