services:
  server:
    image: filebrowser/filebrowser:v2.24.2
    volumes:
      - /:/root
      - server_data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/root

volumes:
  server_data: {}
