services:
  server:
    image: filebrowser/filebrowser:v2.24.2
    volumes:
      - /:/root
      - /:/srv # this prevents filebrowser from making an unnamed volume
      - server_data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/root

networks:
  default:
    name: none
    external: true

volumes:
  server_data: {}
