services:
  server:
    image: filebrowser/filebrowser:v2.24.2
    volumes:
      - /home/pi/device-backend-logs:/home/pi/device-backend-logs
      - /home/pi/device-backend-logs:/srv # this prevents filebrowser from making an unnamed volume
      - server_data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/home/pi/device-backend-logs

networks:
  default:
    name: none
    external: true

volumes:
  server_data: {}
