services:
  server:
    networks:
      - caddy-ingress
    environment:
      - FB_BASEURL=/admin/ps/device-backend-logs/browse
      - FB_NOAUTH=true
    labels:
      caddy: :80
      caddy.redir: /admin/ps/device-backend-logs/browse /admin/ps/device-backend-logs/browse/
      caddy.handle: /admin/ps/device-backend-logs/browse/*
      caddy.handle.reverse_proxy: "{{upstreams 8080}}"

networks:
  caddy-ingress:
    external: true
