#!/bin/bash -eux

machine_name="$(cat /run/machine-name)"

# Load a prefix for the hostname from /etc/hostname-prefix:
if [ -f /etc/hostname-prefix ]; then
  prefix="$(sed -e 's~#.*$~~g' -e '~^$~d' /etc/hostname-prefix)"
else
  prefix=""
fi

mkdir -p /run/overlays/generated/etc
printf "%s%s" "$prefix" "$machine_name" > /run/overlays/generated/etc/hostname
