#!/bin/bash -eux

script_dir="$(dirname $(realpath "$BASH_SOURCE"))"
templates_dir="$script_dir/templates"

machine_name="$(cat /run/machine-name)"

# Update /run/planktoscope/cockpit-origins
mkdir -p /run/planktoscope
cp "$templates_dir/base" /run/planktoscope/cockpit-origins
sed "s/{machine-name}/$machine_name/g" "$templates_dir/machine-name" \
  >> /run/planktoscope/cockpit-origins
if [ -f "/etc/planktoscope/cockpit-origins" ]; then
  sed "s/{machine-name}/$machine_name/g" /etc/planktoscope/cockpit-origins \
    >> /run/planktoscope/cockpit-origins
fi

# FIXME: output into /run/overlays/generated instead!
# Update /etc/cockpit/cockpit.conf
origins="$(sed 's/#.*$//g' /run/planktoscope/cockpit-origins | sed '/^$/d' | paste -s -d ' ')"
sed -i "s~^Origins = .*$~Origins = ${origins}~g" /etc/cockpit/cockpit.conf
