# TODO: make a service which automatically assembles
# /etc/cockpit/cockpit.conf.d files into a
# /run/overlays/generated/etc/cockpit/cockpit.conf file
[WebService]
ProtocolHeader = X-Forwarded-Proto
ForwardedForHeader = X-Forwarded-For
AllowUnencrypted = true
