services:
  reverse-proxy-config:
    image: alpine:3.17.3
    command: sh -c 'while sleep 3600; do :; done'
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.handle_path: /ps/processing/segmenter/streams/object.mjpg
      caddy.handle_path.rewrite: "* /object.mjpg"
      caddy.handle_path.reverse_proxy: host.docker.internal:8001

networks:
  caddy-ingress:
    external: true
