services:
  server:
    image: grafana/grafana-oss:10.1.6
    volumes:
      - server-data:/var/lib/grafana
      - ./provisioning:/provisioning
      - ./dashboards:/provisioned-dashboards
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - GF_PATHS_PROVISIONING=/provisioning
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false

networks:
  default:
    name: none
    external: true

volumes:
  server-data: {}
