services:
  server:
    image: grafana/grafana-oss:10.1.6
    volumes:
      - server-data:/var/lib/grafana
      # TODO: add a volume or mount for grafana datasource+dashboard provisioning, perhaps provided
      # by another container image
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false

networks:
  default:
    name: none
    external: true

volumes:
  server-data: {}
