package:
  description: Metrics monitoring dashboard
  maintainers:
    - name: Ethan Li
      email: lietk12@gmail.com
  license: AGPL-3.0
  sources:
    - https://github.com/grafana/grafana

deployment:
  compose-files: [compose.yml]

features:
  frontend:
    description: Provides access to the GUI
    compose-files: [compose-frontend.yml]
    tags: # TODO: add an entry in device-portal for this
      - device-portal-name=System monitoring dashboard
      - device-portal-description=Provides a graphical dashboard for monitoring system & application metrics
      - device-portal-type=Browser applications
      - device-portal-purpose=System administration and troubleshooting
      - device-portal-entrypoint=/admin/grafana/
    requires:
      networks:
        - description: Overlay network for Caddy to connect to upstream services
          name: caddy-ingress
      services:
        - tags: [caddy-docker-proxy]
          port: 80
          protocol: http
    provides:
      services:
        - description: Monitoring dashboard for Prometheus metrics
          port: 80
          protocol: http
          paths:
            - /admin/grafana
            - /admin/grafana/*
  no-login:
    description: Allows full access without user management or login
    compose-files: [compose-no-login.yml]
